const userInfo = {
    "users": [
    {
    "firstName": "naruto",
    "lastName": "uzumaki",
    "username": "hokage",
    "email": "naruto@5tails.com",
    "password": "#Naruto1234",
    "gender": "m",
    "age": 23,
    "city": "leaf",
    "state": "New York",
    "isAnonymous": true,
    "role": "seeker"
    },
    {
    "firstName": "Sasuke",
    "lastName": "Uchiha",
    "username": "RogueNinja",
    "email": "sasuke@uchiha.com",
    "password": "#Sasuke1234",
    "gender": "m",
    "age": 25,
    "city": "Hidden Sound Village",
    "state": "New York",
    "isAnonymous": false,
    "role": "listener"
    },
    {
    "firstName": "Hinata",
    "lastName": "Hyuga",
    "username": "ByakuganUser",
    "email": "hinata@leaf.com",
    "password": "#Hinata1234",
    "gender": "f",
    "age": 22,
    "city": "Konoha",
    "state": "New York",
    "isAnonymous": true,
    "role": "seeker"
    },
    {
    "firstName": "Shikamaru",
    "lastName": "Nara",
    "username": "Strategist",
    "email": "shikamaru@leaf.com",
    "password": "#Shikamaru1234",
    "gender": "m",
    "age": 26,
    "city": "Konoha",
    "state": "New York",
    "isAnonymous": true,
    "role": "listener"
    },
    {
    "firstName": "Ino",
    "lastName": "Yamanaka",
    "username": "MindTransferUser",
    "email": "ino@leaf.com",
    "password": "#Ino1234",
    "gender": "f",
    "age": 23,
    "city": "Konoha",
    "state": "New York",
    "isAnonymous": true,
    "role": "seeker"
    },
    {
    "firstName": "Kakashi",
    "lastName": "Hatake",
    "username": "CopyNinja",
    "email": "kakashi@leaf.com",
    "password": "#Kakashi1234",
    "gender": "m",
    "age": 31,
    "city": "Konoha",
    "state": "New York",
    "isAnonymous": true,
    "role": "listener"
    },
    {
    "firstName": "Gaara",
    "lastName": "Sabaku",
    "username": "Kazekage",
    "email": "gaara@sand.com",
    "password": "#Gaara1234",
    "gender": "m",
    "age": 27,
    "city": "Hidden Sand Village",
    "state": "New York",
    "isAnonymous": true,
    "role": "seeker"
    },
    {
        "firstName": "Toph",
        "lastName": "Beifong",
        "username": "Metalbender",
        "email": "toph@earth.com",
        "password": "#Toph1234",
        "gender": "f",
        "age": 18,
        "city": "Gaoling",
        "state": "New York",
        "isAnonymous": false,
        "role": "seeker"
        },
        
        {
        "firstName": "Zuko",
        "lastName": "Fire",
        "username": "FireLord",
        "email": "zuko@fire.com",
        "password": "#Zuko1234",
        "gender": "m",
        "age": 20,
        "city": "Fire Nation Capital",
        "state": "New York",
        "isAnonymous": true,
        "role": "listener"
        },
        
        {
        "firstName": "Katara",
        "lastName": "Water",
        "username": "Waterbender",
        "email": "katara@water.com",
        "password": "#Katara1234",
        "gender": "f",
        "age": 19,
        "city": "Southern Water Tribe",
        "state": "New York",
        "isAnonymous": true,
        "role": "seeker"
        },
        
        {
        "firstName": "Aang",
        "lastName": "Air",
        "username": "Avatar",
        "email": "aang@air.com",
        "password": "#Aang1234",
        "gender": "m",
        "age": 112,
        "city": "Air Temple Island",
        "state": "New York",
        "isAnonymous": true,
        "role": "listener"
        },
        
        {
        "firstName": "Sokka",
        "lastName": "Water",
        "username": "Swordsman",
        "email": "sokka@water.com",
        "password": "#Sokka1234",
        "gender": "m",
        "age": 18,
        "city": "Southern Water Tribe",
        "state": "New York",
        "isAnonymous": true,
        "role": "seeker"
        },
        
        {
        "firstName": "Azula",
        "lastName": "Fire",
        "username": "LightningUser",
        "email": "azula@fire.com",
        "password": "#Azula1234",
        "gender": "f",
        "age": 15,
        "city": "Fire Nation Capital",
        "state": "New York",
        "isAnonymous": false,
        "role": "listener"
        },
        
        {
        "firstName": "Appa",
        "lastName": "Sky",
        "username": "SkyBison",
        "email": "appa@air.com",
        "password": "#Appa1234",
        "gender": "m",
        "age": 101,
        "city": "Air Temple Island",
        "state": "New York",
        "isAnonymous": true,
        "role": "seeker"
        },
        {
            "firstName": "Peter",
            "lastName": "Parker",
            "username": "Spiderman",
            "email": "peter@spiderman.com",
            "password": "#Spiderman1234",
            "gender": "m",
            "age": 25,
            "city": "New York",
            "state": "New York",
            "isAnonymous": false,
            "role": "seeker"
            },
            {
            "firstName": "Bruce",
            "lastName": "Wayne",
            "username": "Batman",
            "email": "bruce@wayneenterprises.com",
            "password": "#Batman1234",
            "gender": "m",
            "age": 35,
            "city": "Gotham",
            "state": "New Jersey",
            "isAnonymous": false,
            "role": "listener"
            },
            {
            "firstName": "Clark",
            "lastName": "Kent",
            "username": "Superman",
            "email": "clark@dailyplanet.com",
            "password": "#Superman1234",
            "gender": "m",
            "age": 30,
            "city": "Metropolis",
            "state": "New York",
            "isAnonymous": true,
            "role": "seeker"
            },
            {
            "firstName": "Diana",
            "lastName": "Prince",
            "username": "WonderWoman",
            "email": "diana@themyscira.com",
            "password": "#WonderWoman1234",
            "gender": "f",
            "age": 28,
            "city": "Themyscira",
            "state": "Unknown",
            "isAnonymous": false,
            "role": "listener"
            },
            {
            "firstName": "Steve",
            "lastName": "Rogers",
            "username": "CaptainAmerica",
            "email": "steve@avengers.com",
            "password": "#CaptainAmerica1234",
            "gender": "m",
            "age": 95,
            "city": "New York",
            "state": "New York",
            "isAnonymous": true,
            "role": "seeker"
            },
            {
            "firstName": "Hal",
            "lastName": "Jordan",
            "username": "GreenLantern",
            "email": "hal@glcorp.com",
            "password": "#GreenLantern1234",
            "gender": "m",
            "age": 32,
            "city": "Coast City",
            "state": "California",
            "isAnonymous": true,
            "role": "listener"
            },
            {
            "firstName": "Arthur",
            "lastName": "Curry",
            "username": "Aquaman",
            "email": "arthur@atlantis.com",
            "password": "#Aquaman1234",
            "gender": "m",
            "age": 38,
            "city": "Atlantis",
            "state": "Unknown",
            "isAnonymous": false,
            "role": "seeker"
            },
            {
            "firstName": "Barry",
            "lastName": "Allen",
            "username": "TheFlash",
            "email": "barry@ccpd.com",
            "password": "#TheFlash1234",
            "gender": "m",
            "age": 28,
            "city": "Central City",
            "state": "Missouri",
            "isAnonymous": false,
            "role": "seeker"
        
            },
            {
                "firstName": "Jennie",
                "lastName": "Kim",
                "username": "Jennie",
                "email": "jennie@blackpink.com",
                "password": "#Jennie1234",
                "gender": "f",
                "age": 26,
                "city": "Seoul",
                "state": "South Korea",
                "isAnonymous": true,
                "role": "seeker"
              },
              {
                "firstName": "Jungkook",
                "lastName": "Jeon",
                "username": "Jungkook",
                "email": "jungkook@bts.com",
                "password": "#Jungkook1234",
                "gender": "m",
                "age": 24,
                "city": "Seoul",
                "state": "South Korea",
                "isAnonymous": false,
                "role": "listener"
              },
              {
                "firstName": "Irene",
                "lastName": "Bae",
                "username": "Irene",
                "email": "irene@redvelvet.com",
                "password": "#Irene1234",
                "gender": "f",
                "age": 31,
                "city": "Seoul",
                "state": "South Korea",
                "isAnonymous": true,
                "role": "seeker"
              },
              {
                "firstName": "Jimin",
                "lastName": "Park",
                "username": "Jimin",
                "email": "jimin@bts.com",
                "password": "#Jimin1234",
                "gender": "m",
                "age": 26,
                "city": "Seoul",
                "state": "South Korea",
                "isAnonymous": true,
                "role": "listener"
              },
              {
                "firstName": "Rose",
                "lastName": "Park",
                "username": "Rose",
                "email": "rose@blackpink.com",
                "password": "#Rose1234",
                "gender": "f",
                "age": 24,
                "city": "Seoul",
                "state": "South Korea",
                "isAnonymous": true,
                "role": "seeker"
              },
              {
                "firstName": "J-Hope",
                "lastName": "Jung",
                "username": "J_Hope",
                "email": "jhope@bts.com",
                "password": "#JHope1234",
                "gender": "m",
                "age": 28,
                "city": "Seoul",
                "state": "South Korea",
                "isAnonymous": true,
                "role": "listener"
              },
              {
                "firstName": "Sana",
                "lastName": "Minatozaki",
                "username": "Sana",
                "email": "sana@twice.com",
                "password": "#Sana1234",
                "gender": "f",
                "age": 25,
                "city": "Seoul",
                "state": "South Korea",
                "isAnonymous": false,
                "role": "seeker"
              },
              {
                "firstName": "Jin",
                "lastName": "Kim",
                "username": "Jin",
                "email": "jin@bts.com",
                "password": "#Jin1234",
                "gender": "m",
                "age": 29,
                "city": "Seoul",
                "state": "South Korea",
                "isAnonymous": true,
                "role": "listener"
            },
            {
                "firstName": "Shah Rukh",
                "lastName": "Khan",
                "username": "KingOfBollywood",
                "email": "srk@bollywood.com",
                "password": "#Srk1234",
                "gender": "m",
                "age": 55,
                "city": "Mumbai",
                "state": "Maharashtra",
                "isAnonymous": false,
                "role": "listener"
                },
                {
                "firstName": "Priyanka",
                "lastName": "Chopra",
                "username": "Pri",
                "email": "priyanka@bollywood.com",
                "password": "#Priyanka1234",
                "gender": "f",
                "age": 39,
                "city": "Mumbai",
                "state": "Maharashtra",
                "isAnonymous": false,
                "role": "seeker"
                },
                {
                "firstName": "Akshay",
                "lastName": "Kumar",
                "username": "Khiladi",
                "email": "akshay@bollywood.com",
                "password": "#Akshay1234",
                "gender": "m",
                "age": 54,
                "city": "Mumbai",
                "state": "Maharashtra",
                "isAnonymous": false,
                "role": "listener"
                },
                {
                "firstName": "Deepika",
                "lastName": "Padukone",
                "username": "Deepu",
                "email": "deepika@bollywood.com",
                "password": "#Deepika1234",
                "gender": "f",
                "age": 36,
                "city": "Mumbai",
                "state": "Maharashtra",
                "isAnonymous": false,
                "role": "seeker"
                },
                {
                "firstName": "Amitabh",
                "lastName": "Bachchan",
                "username": "BigB",
                "email": "amitabh@bollywood.com",
                "password": "#Amitabh1234",
                "gender": "m",
                "age": 79,
                "city": "Mumbai",
                "state": "Maharashtra",
                "isAnonymous": false,
                "role": "listener"
                },
                {
                "firstName": "Kareena",
                "lastName": "Kapoor",
                "username": "Bebo",
                "email": "kareena@bollywood.com",
                "password": "#Kareena1234",
                "gender": "f",
                "age": 41,
                "city": "Mumbai",
                "state": "Maharashtra",
                "isAnonymous": false,
                "role": "seeker"
                },
                {
                "firstName": "Salman",
                "lastName": "Khan",
                "username": "Bhaijaan",
                "email": "salman@bollywood.com",
                "password": "#Salman1234",
                "gender": "m",
                "age": 55,
                "city": "Mumbai",
                "state": "Maharashtra",
                "isAnonymous": false,
                "role": "listener"
                }
                   
]
}

export default userInfo;